export const PROPOSICOES_MAP: Record<string, string> = {
  "OF": "Ofício do Congresso Nacional",
  "CON": "Consulta",
  "EMC": "Emenda na Comissão",
  "EMP": "Emenda de Plenário a Projeto em Fase de Discussão do 2º Turno",
  "EMS": "Emenda/Substitutivo do Senado",
  "INC": "Indicação à Mesa",
  "MSC": "Mensagem de ausência do país por mais de 15 dias",
  "PDC": "Projeto de Decreto Legislativo de Sustação de Atos Normativos do Poder Executivo",
  "PEC": "Proposta de Emenda à Constituição",
  "PET": "Petição",
  "PFC": "Proposta de Fiscalização e Controle",
  "PL": "Projeto de Lei",
  "PLP": "Projeto de Lei Complementar",
  "PRC": "Projeto de Resolução de Alteração do Regimento e outros",
  "PRN": "Projeto de Resolução do Congresso Nacional",
  "RCP": "Requerimento de Instituição de CPI",
  "REC": "Recurso contra aplicação de censura escrita (Art. 12, § 2º do CEDP)",
  "REM": "Reclamação",
  "REP": "Representação",
  "REQ": "Requerimento de Apresentação de Projeto de Lei Rejeitado na mesma Sessão Legislativa",
  "RIC": "Requerimento de Informação",
  "SIT": "Solicitação de Informação ao TCU",
  "TVR": "Renovação Rádio Ondas Médias Local adaptada para Frequência Modulada",
  "INA": "Indicação de Autoridade",
  "P.C": "Parecer (CD)",
  "PAR": "Parecer de Comissão",
  "MAN": "Manifestação pela Incompetência da Comissão",
  "PRL": "Parecer do Relator",
  "PRV": "Parecer Vencedor",
  "PPP": "Parecer Proferido em Plenário - Notas Taquigráficas",
  "PRR": "Parecer Reformulado",
  "CVO": "Complementação de Voto",
  "PES": "Parecer às Emendas Apresentadas ao Substitutivo do Relator",
  "RDF": "Redação Final",
  "PRF": "Projeto de Resolução do Senado Federal",
  "CST": "Solicitação de Pronunciamento",
  "SGM": "Ofício da Mesa",
  "DIS": "Discurso",
  "SBT": "Substitutivo",
  "SBE": "Subemenda",
  "EMR": "Emenda de Relator",
  "ESB": "Emenda ao Substitutivo",
  "VTS": "Voto em Separado",
  "DTQ": "Destaque para Votação em Separado",
  "REL": "Relatório do Congresso Nacional",
  "DTN": "Destaque (CN)",
  "DVT": "Declaração de Voto",
  "EML": "Emenda à LDO",
  "SDL": "Sugestão de Emenda à LDO - CLP",
  "SUG": "Sugestão",
  "SUM": "Súmula",
  "EMO": "Emenda ao Orçamento",
  "SOA": "Sugestão de Emenda ao Orçamento - CLP",
  "MPV": "Medida Provisória de Crédito Extraordinário",
  "DEN": "Denúncia",
  "RPD": "Requerimento de Encerramento da Discussão e do Encaminhamento de Matéria Urgente",
  "AV": "Demonstrativo de emissão do real",
  "DCR": "Denúncia por Crime de Responsabilidade",
  "PEP": "Parecer às Emendas de Plenário",
  "PSS": "Parecer às Emendas ou ao Substitutivo do Senado - Notas Taquigráficas",
  "NIC": "Norma Interna",
  "ERD": "Emenda de Redação em Plenário",
  "PPR": "Parecer Reformulado de Plenário às Emendas de Plenário",
  "TER": "Termo de Implementação",
  "RLP": "Relatório Preliminar",
  "RLF": "Relatório Final",
  "PRT": "Parecer Técnico",
  "PRO": "Proposta de Regulamento",
  "OBJ": "Objeto de Deliberação",
  "PLS": "Projeto de Lei do Senado Federal",
  "PLC": "Projeto de Lei da Câmara dos Deputados (SF)",
  "PDS": "Projeto de Decreto Legislativo (SF)",
  "RDV": "Redação do Vencido",
  "RST": "Redação para o segundo turno",
  "RLP(R)": "Relatório Prévio Reformulado",
  "EPP": "Emenda ao Plano Plurianual",
  "EAG": "Emenda Substitutiva Aglutinativa Global",
  "PEA": "Parecer à Emenda Aglutinativa",
  "SPA": "Sugestão de Emenda ao PPA - CLP",
  "PR": "Projeto de Resolução",
  "IAN": "Indicação da ANC (1987-88)",
  "PCA": "Parecer da ANC (1987-88)",
  "PDA": "Projeto de Decisão da ANC (1987-88)",
  "PRA": "Projeto de Resolução da ANC (1987-88)",
  "RCM": "Requerimento de Comissão Mista",
  "RQA": "Requerimento de Informações da ANC (1987-88)",
  "RQC": "Requerimento de Convocação",
  "AA": "Autógrafo",
  "ESP": "Emenda Substitutiva de Plenário",
  "SSP": "Subemenda Substitutiva de Plenário",
  "MMP": "Mensagem (MPU)",
  "RIN": "Requerimento de Resolução Interna",
  "MST": "Mensagem (STF)",
  "APJ": "Anteprojeto",
  "RQN": "Requerimento do Congresso Nacional",
  "R.C": "Recurso do Congresso Nacional",
  "CCN": "Consulta do Congresso Nacional",
  "ADD": "Adendo",
  "DEC": "Decisão",
  "ATC": "Ato Convocatório",
  "PRST": "Parecer à Redação para o Segundo Turno",
  "RLP(V)": "Relatório Prévio Vencedor",
  "EMA": "Emenda Aglutinativa Substitutiva",
  "DOC": "Alteração em Frente Parlamentar Registrada na Câmara dos Deputados",
  "SOR": "Sugestão de Emenda ao Orçamento - Comissões",
  "SLD": "Sugestão de Emenda à LDO - Comissões",
  "SPP": "Sugestão de Emenda ao PPA - Comissões",
  "RPA": "Relatório Parcial",
  "MTC": "Mensagem (TCU)",
  "SPP-R": "Sugestão de Emenda ao PPA - revisão (Comissões)",
  "SPA-R": "Sugestão de Emenda ao PPA - revisão (CLP)",
  "RFP": "Refomulação de Parecer - art. 130, parágrafo único do RICD.",
  "PRVP": "Proposta de Redação do Vencido em Primeiro Turno",
  "SUC": "Sugestão a Projeto de Consolidação de Leis",
  "PLN": "Projeto de Lei (CN) de Plano Plurianual",
  "PDN": "Projeto de Decreto Legislativo (CN)",
  "AVN": "Aviso (CN) de Subtítulos com Indícios de Irregularidades Graves Apontadas pelo TCU",
  "MCN": "Mensagem (CN) de Relatório de Avaliação de Receitas e Despesas, MCN",
  "OFN": "Ofício (CN) de Demonstrações Contábeis de Fundo Constitucional de Financiamento do Nordeste (FNE).",
  "MSF": "Mensagem (SF)",
  "PRP": "Parecer do Relator Parcial",
  "EMRP": "Emenda de Relator Parcial",
  "CAC": "Comunicado de Alteração do Controle Societário",
  "RRL": "Relatório do Relator (CMO)",
  "CVR": "Contestação ao Voto do Relator",
  "PARF": "Parecer de Comissão para Redação Final",
  "SRL": "Sugestão a Relatório (CN)",
  "RRC": "Relatório de Receita",
  "RPLE": "Relatório Preliminar Apresentado com Emendas",
  "ERR": "Errata",
  "CAE": "Relatório do Comitê de Admissibilidade de Emendas (CAE)",
  "COI": "Relatório do COI",
  "RAT": "Relatório Setorial",
  "OFS": "Ofício do Senado Federal de Fundo Constitucional de Financiamento ",
  "MSG": "Mensagem (SF) de Contas do Governo da República",
  "SBT-A": "Substitutivo adotado pela Comissão",
  "EMC-A": "Emenda Adotada pela Comissão",
  "SBE-A": "Subemenda Adotada pela Comissão",
  "RPLOA": "Relatório Preliminar",
  "ANEXO": "Anexo",
  "EMPV": "Emenda à Medida Provisória (CN)",
  "SBR": "Subemenda de Relator",
  "ERD-A": "Emenda de Redação Adotada",
  "PIN": "Proposta de Instrução Normativa",
  "PROC": "Processo Interno",
  "ATA": "Ata",
  "CRVITAEDOC": "Curriculum Vitae/Outro Documento",
  "PR/CNMP": "Parecer do Conselho Nacional do Ministério Público",
  "PR/CNJ": "Parecer do Conselho Nacional de Justiça",
  "DOCCPI": "Documento de CPI sigiloso",
  "OFJ": "Ofício de Órgão do Poder Judiciário",
  "OFE": "Ofício de Órgão do Poder Executivo",
  "MAD": "Manifestação do(a) Denunciado(a)",
  "SIP": "Solicitação para instauração de processo",
  "RCEX": "Relatório de Comissão Externa",
  "RCEL": "Relatório de Comissão de Estudo Legislativo",
  "DEF": "Complementação de Defesa",
  "PRLP": "Parecer Preliminar de Plenário",
  "PRLP(V)": "Parecer Preliminar Vencedor",
  "RGT": "Relatório de Grupo de Trabalho",
  "REL-A": "Relatório Adotado pela Comissão",
  "RRR": "Relatório Reformulado",
  "RVC": "Relatório Vencedor",
  "CMC": "Comunicação de Medida Cautelar",
  "MIP": "Minuta de Proposição Legislativa",
  "ECN": "Emenda (CN)",
  "DTS": "Destaque Simples",
  "RPDR": "Votação Nominal do Requerimento de Alteração da Ordem dos Trabalhos",
  "AJECN": "Ajuste de Emenda Orçamentária (CN)",
  "ATACN": "Ata (CN)",
  "PRLE": "Parecer Preliminar às Emendas de Plenário",
  "RLG": "Relatório Geral",
  "QO": "Questão de Ordem",
  "APM": "Complemento de Apoiamento",
  "CFIS": "Relatório de Atividades do Comitê de Avaliação, Fiscalização e Controle de Execução Orçamentária",
  "ATA_PRE": "Ata Preparatória",
  "SAP": "Sustação de Andamento de Ação Penal",
  "OFM": "Ofício à Mesa"
};
